### ISSUE TITLE
Post edit screen Metabox

### ISSUE THREAD

**Issue by StaggerLeee** [avocadesign/torlesse-genesis#1]
Hi Brendyn,

sorry for using issue to contact you, be free to delete it after reading.

Would like just to ask if you can be friendly to share your snippet for custom Post edit screen Metabox you used in this example in Gutenberg discussion:

https://user-images.githubusercontent.com/782819/29646655-e37d54d2-88d8-11e7-81d6-6e032e542ad1.png

(yellow, brownish one)

Namely I did replicate it, somehow. Problem I have is that Metabox header is hidden by CSS and is visible for short time on page refresh.

Sorry again, delete this issue after reading. If you decide to share this PHP snippet leave it here and I can close issue, later you can delete it.

@avocadesign

**Comment by avocadesign** [comment]
Hi, there’s no PHP involved. It’s just an ACF message field with HTML in it, set to appear in the sidebar, that I’ve styled up with CSS to stand out. The CSS is being implemented through an custom admin theme called “clientside”.

Cheers

Brendyn Montgomery
Creative Director
w: avoca.design
p: 03 929 5125 m: 021 186 7894
Helping you choose the best path online

**Comment by StaggerLeee** [comment]
Thank you, will try it. You can delete issue now.
